name: Test Demo
run-name: Test
on: [push]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # You can change the runner platform if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # This action checks out your code repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Set the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./test/requirements.txt  # If you have a requirements file

      - name: Run Tests
        run: |
      		cd ./test
      		python test.py  # Run your test script

      # You can add more steps here if needed, such as publishing test results
